<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NebuCtx.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Sqlite\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NebuCtx.Contracts\NebuCtx.Contracts.csproj" />
  </ItemGroup>

</Project>
