<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NebuCtx.DataRepair</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NebuCtx.Contracts\NebuCtx.Contracts.csproj" />
    <ProjectReference Include="..\..\src\NebuCtx.Server.Core\NebuCtx.Server.Core.csproj" />
    <ProjectReference Include="..\..\src\NebuCtx.Storage\NebuCtx.Storage.csproj" />
  </ItemGroup>

</Project>
