FROM docker.io/library/ubuntu:noble
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends jq ca-certificates curl libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY target/release/nebula-ctx /usr/local/bin/nebula-ctx
COPY homeassistant/run.sh /run.sh

RUN sed -i 's/\r$//' /run.sh \
    && chmod +x /run.sh \
    && mkdir -p /data

EXPOSE 4242 3333

CMD ["/run.sh"]
