<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>NebuCtx.Server.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NebuCtx.Contracts\NebuCtx.Contracts.csproj" />
    <ProjectReference Include="..\NebuCtx.Server.Core\NebuCtx.Server.Core.csproj" />
    <ProjectReference Include="..\NebuCtx.Storage\NebuCtx.Storage.csproj" />
    <ProjectReference Include="..\NebuCtx.Tools\NebuCtx.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Dashboard\dashboard.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="Dashboard\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="Dashboard\favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
