<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NebuCtx.Tools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NebuCtx.Contracts\NebuCtx.Contracts.csproj" />
    <ProjectReference Include="..\NebuCtx.Server.Core\NebuCtx.Server.Core.csproj" />
  </ItemGroup>

</Project>
